name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [ 8, 11, 17 ]
    env:
      VERSION_POSTFIX: "-SNAPSHOT"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Java ${{ matrix.jdk-version }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: 'adopt'

      - name: Gradle cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.gradle
          key: gradle

      - name: Build library
        run: ./gradlew build publishToMavenLocal --warning-mode all

      - name: Build gradle plugin
        run: ./gradlew -p plugins/gradle/graphql-java-codegen-gradle-plugin build publishToMavenLocal --warning-mode all

      - name: Build gradle example-server
        run: ./gradlew -p plugins/gradle/example-server test --warning-mode all

      - name: Build gradle example-client
        run: ./gradlew -p plugins/gradle/example-client test --warning-mode all

      - name: Build gradle example-client-kotlin
        run: ./gradlew -p plugins/gradle/example-client-kotlin build --warning-mode all
