name: Release Snapshot

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Java 17
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Gradle cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.gradle
          key: gradle

      - name: Compute snapshot version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION_POSTFIX=-BUILD-$(git rev-parse HEAD)" >> "$GITHUB_ENV"
          else
            echo "VERSION_POSTFIX=-SNAPSHOT-$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_ENV"
          fi

      - name: Publish library snapshot to GitHub Packages
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_ACTOR: "${{ github.actor }}"
        run: |
          ./gradlew publishToMavenLocal publish --warning-mode all

      - name: Publish Gradle plugin snapshot to GitHub Packages
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_ACTOR: "${{ github.actor }}"
        run: |
          ./gradlew -p plugins/gradle/graphql-java-codegen-gradle-plugin publish --warning-mode all
