name: Release Snapshot

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Java 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.6.0
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Gradle cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.2.1
        with:
          path: ~/.gradle
          key: gradle

      - name: Compute snapshot version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION_POSTFIX=-BUILD-$(git rev-parse HEAD)" >> "$GITHUB_ENV"
          else
            echo "VERSION_POSTFIX=-SNAPSHOT-$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_ENV"
          fi

      - name: Publish library snapshot to GitHub Packages
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_ACTOR: "${{ github.actor }}"
        run: |
          ./gradlew publishToMavenLocal publish --warning-mode all

      - name: Publish Gradle plugin snapshot to GitHub Packages
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_ACTOR: "${{ github.actor }}"
        run: |
          ./gradlew -p plugins/gradle/graphql-java-codegen-gradle-plugin publish --warning-mode all
